Downloader:
  proxies: null
  timeout: 10
  encoding: utf-8
NovelDownloader:
  ctl_dl_cover: false
  ctl_append_title_when_dl_chapter: true
  ctl_dl_delay: 1
  pool_num: 1
Website:
  url: www.qidian.com
