Downloader:
  proxies: null
  timeout: 10
  encoding: gbk
  headers: 
    user-agent: 'Mozilla/5.0 (Macintosh Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36'
NovelDownloader:
  ctl_dl_delay: 1
  pool_num: 1
Website:
  url: www.qiuwu.net
