'0':
  author: 長戟大兜2
  bookname: 超凡貴族
  chaps: 725
  chaps_old: 717
  cover: null
  dir: data\www.b5200.net\[長戟大兜2] 超凡貴族
  id: '0'
  last_check: 2020-05-11 01:42
  last_update: 2020-05-11 01:42
  update_time: '2020-05-10'
  url: http://www.b5200.net/69_69905/
'1':
  author: 愛潛水的烏賊
  bookname: 詭祕之主
  chaps: 10
  chaps_old: 10
  cover: null
  dir: data\www.qidian.com\[爱潜水的乌贼] 诡秘之主
  id: '1'
  last_check: 2020-04-23 23:38
  last_update: 2020-04-23 21:47
  update_time: '2018-05-31 19:08:55'
  url: https://book.qidian.com/info/1010868264/
'10':
  author: 賣報小郎君
  bookname: 大奉打更人
  chaps: 311
  chaps_old: 311
  cover: null
  dir: data\www.b5200.net\[卖报小郎君] 大奉打更人
  id: '10'
  last_check: 2020-08-01 12:41
  last_update: 2020-08-01 12:41
  update_time: '2020-07-31'
  url: http://www.b5200.net/131_131878/
'11':
  author: 榮小榮
  bookname: 大周仙吏
  chaps: 165
  chaps_old: 165
  cover: null
  dir: data\www.b5200.net\[荣小荣] 大周仙吏
  id: '11'
  last_check: 2020-08-22 12:10
  last_update: 2020-08-22 12:10
  update_time: '2020-08-21'
  url: http://www.b5200.net/135_135435/
'12':
  author: 三腳架
  bookname: 黑石密碼
  chaps: 180
  chaps_old: 139
  cover: null
  dir: data\www.b5200.net\[三脚架] 黑石密码
  id: '12'
  last_check: 2020-08-23 16:24
  last_update: 2020-08-23 16:24
  update_time: '2020-08-23'
  url: http://www.b5200.net/135_135194/
'13':
  author: 惰墮
  bookname: 劍卒過河
  chaps: 179
  chaps_old: 179
  cover: null
  dir: data\www.b5200.net\[惰堕] 剑卒过河
  id: '13'
  last_check: 2020-08-04 23:12
  last_update: 2020-08-04 23:12
  update_time: '2020-08-04'
  url: http://www.b5200.net/135_135599/
'14':
  author: 吾道長不孤
  bookname: 賽博英雄傳
  chaps: 257
  chaps_old: 239
  cover: null
  dir: data\www.b5200.net\[吾道长不孤] 赛博英雄传
  id: '14'
  last_check: 2020-08-22 13:15
  last_update: 2020-08-22 13:15
  update_time: '2020-08-22'
  url: http://www.b5200.net/130_130503/
'15':
  author: 閻ZK
  bookname: 我在幕後調教大佬
  chaps: 275
  chaps_old: 275
  cover: null
  dir: data\www.b5200.net\[阎ZK] 我在幕后调教大佬
  id: '15'
  last_check: 2020-08-07 20:43
  last_update: 2020-08-07 20:43
  update_time: '2020-08-07'
  url: http://www.b5200.net/132_132959/
'16':
  author: 雲中殿
  bookname: 我真的不是氣運之子
  chaps: 295
  chaps_old: 295
  cover: null
  dir: data\www.b5200.net\[云中殿] 我真的不是气运之子
  id: '16'
  last_check: 2020-08-08 12:13
  last_update: 2020-08-08 12:13
  update_time: '2020-08-08'
  url: http://www.b5200.net/132_132948/
'17':
  author: 北海牧鯨
  bookname: 超凡大航海
  chaps: 254
  chaps_old: 254
  cover: null
  dir: data\www.b5200.net\[北海牧鲸] 超凡大航海
  id: '17'
  last_check: 2020-08-08 12:22
  last_update: 2020-08-08 12:22
  update_time: '2020-08-07'
  url: http://www.b5200.net/134_134475/
'18':
  author: 南朝近衛
  bookname: 仿生紀元
  chaps: 249
  chaps_old: 249
  cover: null
  dir: data\www.b5200.net\[南朝近卫] 仿生纪元
  id: '18'
  last_check: 2020-08-18 00:01
  last_update: 2020-08-18 00:01
  update_time: '2020-08-17'
  url: http://www.b5200.net/135_135499/
'19':
  author: 乘風御劍
  bookname: 劍仙三千萬
  chaps: 64
  chaps_old: 64
  cover: null
  dir: data\www.b5200.net\[乘风御剑] 剑仙三千万
  id: '19'
  last_check: 2020-08-18 00:03
  last_update: 2020-08-18 00:03
  update_time: '2020-08-17'
  url: http://www.b5200.net/136_136860/
'2':
  author: 乘風御劍
  bookname: 咫尺之間人盡敵國
  chaps: 10
  chaps_old: 10
  cover: null
  dir: data\www.67shu.net\[乘风御剑] 咫尺之间人尽敌国
  id: '2'
  last_check: 2020-04-26 18:58
  last_update: 2020-04-23 23:22
  update_time: 2020-04-26 12:03
  url: https://www.67shu.net/112/112092/
'3':
  author: 楚白
  bookname: 夏逆
  chaps: 10
  chaps_old: 10
  cover: null
  dir: data\www.ranwen.la\[楚白] 夏逆
  id: '3'
  last_check: 2020-04-29 20:32
  last_update: 2020-04-29 20:32
  update_time: '2020-04-28 00:04:32'
  url: https://www.ranwen.la/files/article/89/89698/
'4':
  author: 斜線和絃
  bookname: 飛越泡沫時代
  chaps: 512
  chaps_old: 512
  cover: null
  dir: data\www.b5200.net\[斜线和弦] 飞越泡沫时代
  id: '4'
  last_check: 2020-05-11 00:47
  last_update: 2020-05-11 00:47
  update_time: '2020-05-10'
  url: http://www.b5200.net/116_116035/
'5':
  author: 甲青
  bookname: 蜀漢之莊稼漢
  chaps: 809
  chaps_old: 809
  cover: null
  dir: data\www.b5200.net\[甲青] 蜀汉之庄稼汉
  id: '5'
  last_check: 2020-05-15 21:54
  last_update: 2020-05-15 20:21
  update_time: '2020-05-14'
  url: http://www.b5200.net/101_101383/
'6':
  author: 綠嬑
  bookname: 生存[末世]
  chaps: 482
  chaps_old: 482
  cover: null
  dir: data\www.qiuwu.net\[绿嬑] 生存[末世]
  id: '6'
  last_check: 2020-05-23 11:16
  last_update: 2020-05-23 11:16
  update_time: '2018-09-16'
  url: http://www.qiuwu.net/html/339/339017/
'7':
  author: 佛前獻花
  bookname: 神祕復甦
  chaps: 735
  chaps_old: 735
  cover: null
  dir: data\www.67shu.net\[佛前献花] 神秘复苏
  id: '7'
  last_check: 2020-06-21 23:56
  last_update: 2020-06-21 23:56
  update_time: 2020-06-21 21:48
  url: https://www.67shu.net/112/112761/
'8':
  author: 範馬加藤惠
  bookname: 我在東京教劍道
  chaps: 203
  chaps_old: 203
  cover: null
  dir: data\www.b5200.net\[范马加藤惠] 我在东京教剑道
  id: '8'
  last_check: 2020-08-03 23:49
  last_update: 2020-08-03 23:49
  update_time: '2020-08-03'
  url: http://www.b5200.net/135_135514/
'9':
  author: 臥牛真人
  bookname: 地球人實在太凶猛了
  chaps: 277
  chaps_old: 277
  cover: null
  dir: data\www.b5200.net\[卧牛真人] 地球人实在太凶猛了
  id: '9'
  last_check: 2020-07-18 13:07
  last_update: 2020-07-18 13:07
  update_time: '2020-07-18'
  url: http://www.b5200.net/133_133241/
