'0':
  author: 惰堕
  bookname: 剑徒之路
  chaps: 10
  dir: data\www.b5200.net\[惰堕] 剑徒之路
  id: '0'
  last_check: 2020-04-12 23:45
  last_update: 2020-04-12 02:49
  update_time: '2020-04-12'
  url: http://www.b5200.net/101_101696/
'1':
  author: 造化斋主
  bookname: 真气时代
  chaps: 10
  dir: data\www.qiuwu.net\[造化斋主] 真气时代
  id: '1'
  last_check: 2020-04-12 23:43
  last_update: 2020-04-12 02:55
  update_time: '2020-03-18'
  url: https://www.qiuwu.net/html/449/449302/
