AozoraEpub3_device: kindle
AozoraEpub3_hor: false
AozoraEpub3_path: D:\download\kindle\narou-develop\narou\libkindle\AozoraEpub3-1.1.0b46\
kindlegen_compresslevel: c1
kindlegen_path: D:\download\kindle\narou-develop\narou\libkindle\AozoraEpub3-1.1.0b46\
opencc: s2twp
mtp_device : Pixel 3 XL
mtp_copyto : Download
