AozoraEpub3_device: kindle
AozoraEpub3_enc: UTF-8
AozoraEpub3_hor: true
AozoraEpub3_path: D:\download\kindle\narou-develop\narou\libkindle\AozoraEpub3-1.1.0b46
kindlegen_compresslevel: c1
kindlegen_path: D:\download\kindle\narou-develop\narou\libkindle\AozoraEpub3-1.1.0b46
