AozoraEpub3_device: kindle
AozoraEpub3_enc: UTF-8
AozoraEpub3_hor: true
AozoraEpub3_path: C:\Users\danny_tsai\web\extra
kindlegen_compresslevel: c1
kindlegen_path: C:\Users\danny_tsai\web\extra
